remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: CARDIAL-nyu
description: Cardiac Imaging and Analysis Laboratory @ New York University, Grossman School of Medicine
logo: /cover.png
show_downloads: true
